version: "3.8" # docker-composeのバージョン選択
services:
  menhera_test: # サービス名
    build: # Dockerfileの設定
      context: . # Dockerfileがあるディレクトリ
      dockerfile: Dockerfile # Dockerfileの名前
    volumes: # データの永続化
      - ./:/app:cached # ホストのカレントディレクトリとコンテナ内の作業ディレクトリを同期
      - /app/node_modules/
    environment: # 環境変数
      - HOST=0.0.0.0 # localhost接続をする際に必要
      - CHOKIDAR_USEPOLLING=true # ホットリロードを可能にする
    ports: # ホストのポートとコンテナのポートを接続
      - "5173:5173"
    command: yarn dev # 実行コマンド
